#!/usr/bin/env python3
""" Prime Factor numbers """
from sys import argv
from math import sqrt


def open_read_file(file_name):
    """read from file
    add to array
    """
    with open(file_name, "r", encoding="utf-8") as file:
        lines = file.readlines()
    number_to_factor = []
    for line in lines:
        number_to_factor.append(int(line))
    return number_to_factor


def is_prime(n):
    """check if integer n is a prime"""
    if n <= 1:
        return False
    if n <= 3:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6
    return True


def find_prime_factors(n):
    """factor each
    n given
    """
    for i in range(2, int(sqrt(n)) + 1):
        if n % i == 0:
            if is_prime(i) and is_prime(n // i):
                print("{}={}*{}".format(n, i, n // i))
                break


def fac_list(ls):
    """factor each
    num in ls
    """
    for i in ls:
        find_prime_factors(i)


if len(argv) == 2:
    fac_list(open_read_file(argv[1]))
